// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igijjaavfcpnqzaqejdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnaWpqYWF2ZmNwbnF6YXFlamRuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0Njc3MTAsImV4cCI6MjA2MDA0MzcxMH0.40dAzgYYm-sQNj5Nz1dg_vWqsX-bKmBgGoRIh1KEqA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);